<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mono.Cecil" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edgar\Edgar.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <Target Name="CustomAfterBuild" AfterTargets="Build">
    <PropertyGroup>
      <RepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\..'))</RepositoryRoot>
      <EdgarOutputDirectory>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\Edgar\bin\$(Configuration)\netstandard2.0'))</EdgarOutputDirectory>
      <WorkingDirectory>$(TargetDir)</WorkingDirectory>
      <MergedDirectory>$(WorkingDirectory)EdgarSingleFile</MergedDirectory>
      <ModifiedDirectory>$(WorkingDirectory)EdgarSingleFileModified</ModifiedDirectory>
      <MergedAssembly>$(MergedDirectory)\EdgarSingleFile.dll</MergedAssembly>
      <ModifiedAssembly>$(ModifiedDirectory)\EdgarSingleFile.dll</ModifiedAssembly>
    </PropertyGroup>

    <ItemGroup>
      <MergeDependency Include="BenchmarkUtils;
                                GraphPlanarityTesting;
                                Newtonsoft.Json;
                                RangeTree;
                                System.Drawing.Common;
                                YamlDotNet" />
      <CopyItems Include="$(EdgarOutputDirectory)\Edgar.dll" />
      <CopyItems Include="@(MergeDependency->'$(EdgarOutputDirectory)\%(Identity).dll')" />
    </ItemGroup>

    <RemoveDir Directories="$(WorkingDirectory)Edgar;$(MergedDirectory);$(ModifiedDirectory)" />
    <MakeDir Directories="$(WorkingDirectory)Edgar;$(MergedDirectory);$(ModifiedDirectory)" />
    <Copy SourceFiles="@(CopyItems)" DestinationFolder="$(WorkingDirectory)Edgar" />

    <ItemGroup>
      <MergeAssemblies Include="@(MergeDependency->'$(WorkingDirectory)Edgar\%(Identity).dll')" />
    </ItemGroup>

    <Exec Command="dotnet tool restore" WorkingDirectory="$(RepositoryRoot)" />
    <Exec Command="dotnet tool run ilrepack -- /target:library /internalizeassembly:Newtonsoft.Json /lib:&quot;$(WorkingDirectory)Edgar&quot; /out:&quot;$(MergedAssembly)&quot; &quot;$(WorkingDirectory)Edgar\Edgar.dll&quot; @(MergeAssemblies->'&quot;%(FullPath)&quot;', ' ')" WorkingDirectory="$(RepositoryRoot)" />
    <Exec Command="dotnet &quot;$(TargetPath)&quot; &quot;$(MergedAssembly)&quot; &quot;$(ModifiedAssembly)&quot;" />
  </Target>

</Project>
