// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LayoutContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode>? _RoomTemplateRepeatMode;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode> RoomTemplateRepeatMode
        {
            get => _RoomTemplateRepeatMode ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode> Create_RoomTemplateRepeatMode(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode> jsonTypeInfo))
            {
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.GetEnumConverter<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode>(options));
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
