// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LayoutContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>>? _LayoutGrid2DInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>> LayoutGrid2DInt32
        {
            get => _LayoutGrid2DInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>> Create_LayoutGrid2DInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>((global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>)args[0]),
                    PropertyMetadataInitializer = _ => LayoutGrid2DInt32PropInit(options),
                    ConstructorParameterMetadataInitializer = LayoutGrid2DInt32CtorParamInit,
                    SerializeHandler = LayoutGrid2DInt32SerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] LayoutGrid2DInt32PropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[1];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>)obj).Rooms,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Rooms",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>>(options, info0);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void LayoutGrid2DInt32SerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WritePropertyName(PropName_Rooms);
            ListLayoutRoomGrid2DInt32SerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutGrid2D<int>)value).Rooms);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] LayoutGrid2DInt32CtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[1];

            parameters[0] = new()
            {
                Name = "rooms",
                ParameterType = typeof(global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>)
            };
            
            return parameters;
        }
    }
}
