// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LayoutContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>? _LayoutDoorGrid2DInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>> LayoutDoorGrid2DInt32
        {
            get => _LayoutDoorGrid2DInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>> Create_LayoutDoorGrid2DInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>((int)args[0], (int)args[1], (global::Edgar.Geometry.OrthogonalLineGrid2D)args[2], (global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)args[3], (global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)args[4]),
                    PropertyMetadataInitializer = _ => LayoutDoorGrid2DInt32PropInit(options),
                    ConstructorParameterMetadataInitializer = LayoutDoorGrid2DInt32CtorParamInit,
                    SerializeHandler = LayoutDoorGrid2DInt32SerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] LayoutDoorGrid2DInt32PropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[5];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)obj).FromRoom,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "FromRoom",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)obj).ToRoom,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "ToRoom",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.OrthogonalLineGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)obj).DoorLine,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "DoorLine",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.OrthogonalLineGrid2D>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)obj).Socket,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Socket",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>(options, info3);

            var info4 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)obj).Type,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Type",
                JsonPropertyName = null
            };
            
            properties[4] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>(options, info4);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void LayoutDoorGrid2DInt32SerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_FromRoom, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)value).FromRoom);
            writer.WriteNumber(PropName_ToRoom, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)value).ToRoom);
            writer.WritePropertyName(PropName_DoorLine);
            OrthogonalLineGrid2DSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)value).DoorLine);
            writer.WritePropertyName(PropName_Socket);
            IDoorSocketSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)value).Socket);
            writer.WritePropertyName(PropName_Type);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>)value).Type, DoorType);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] LayoutDoorGrid2DInt32CtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[5];

            parameters[0] = new()
            {
                Name = "fromRoom",
                ParameterType = typeof(int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            parameters[1] = new()
            {
                Name = "toRoom",
                ParameterType = typeof(int),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            parameters[2] = new()
            {
                Name = "doorLine",
                ParameterType = typeof(global::Edgar.Geometry.OrthogonalLineGrid2D),
                Position = 2,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.OrthogonalLineGrid2D)
            };
            
            parameters[3] = new()
            {
                Name = "socket",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket),
                Position = 3,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)
            };
            
            parameters[4] = new()
            {
                Name = "type",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.DoorType),
                Position = 4,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)
            };
            
            return parameters;
        }
    }
}
