// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LayoutContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>? _LayoutRoomGrid2DInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>> LayoutRoomGrid2DInt32
        {
            get => _LayoutRoomGrid2DInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>> Create_LayoutRoomGrid2DInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>((int)args[0], (global::Edgar.Geometry.PolygonGrid2D)args[1], (global::Edgar.Geometry.Vector2Int)args[2], (bool)args[3], (global::Edgar.GraphBasedGenerator.Grid2D.RoomTemplateGrid2D)args[4], (global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D)args[5], (global::Edgar.Geometry.TransformationGrid2D)args[6]),
                    PropertyMetadataInitializer = _ => LayoutRoomGrid2DInt32PropInit(options),
                    ConstructorParameterMetadataInitializer = LayoutRoomGrid2DInt32CtorParamInit,
                    SerializeHandler = LayoutRoomGrid2DInt32SerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] LayoutRoomGrid2DInt32PropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[8];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Room,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Room",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = null,
                Setter = null,
                IgnoreCondition = global::System.Text.Json.Serialization.JsonIgnoreCondition.Always,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "RoomDescription",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.PolygonGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Outline,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Outline",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.PolygonGrid2D>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Position,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Position",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info3);

            var info4 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.RoomTemplateGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).RoomTemplate,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "RoomTemplate",
                JsonPropertyName = null
            };
            
            properties[4] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Grid2D.RoomTemplateGrid2D>(options, info4);

            var info5 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<bool>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).IsCorridor,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "IsCorridor",
                JsonPropertyName = null
            };
            
            properties[5] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<bool>(options, info5);

            var info6 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Doors,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Doors = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Doors",
                JsonPropertyName = null
            };
            
            properties[6] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.LayoutDoorGrid2D<int>>>(options, info6);

            var info7 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.TransformationGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)obj).Transformation,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Transformation",
                JsonPropertyName = null
            };
            
            properties[7] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.TransformationGrid2D>(options, info7);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void LayoutRoomGrid2DInt32SerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_Room, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).Room);
            writer.WritePropertyName(PropName_Outline);
            PolygonGrid2DSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).Outline);
            writer.WritePropertyName(PropName_Position);
            Vector2IntSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).Position);
            writer.WritePropertyName(PropName_RoomTemplate);
            RoomTemplateGrid2DSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).RoomTemplate);
            writer.WriteBoolean(PropName_IsCorridor, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).IsCorridor);
            writer.WritePropertyName(PropName_Doors);
            ListLayoutDoorGrid2DInt32SerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).Doors);
            writer.WritePropertyName(PropName_Transformation);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LayoutRoomGrid2D<int>)value).Transformation, TransformationGrid2D);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] LayoutRoomGrid2DInt32CtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[7];

            parameters[0] = new()
            {
                Name = "room",
                ParameterType = typeof(int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            parameters[1] = new()
            {
                Name = "outline",
                ParameterType = typeof(global::Edgar.Geometry.PolygonGrid2D),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.PolygonGrid2D)
            };
            
            parameters[2] = new()
            {
                Name = "position",
                ParameterType = typeof(global::Edgar.Geometry.Vector2Int),
                Position = 2,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.Vector2Int)
            };
            
            parameters[3] = new()
            {
                Name = "isCorridor",
                ParameterType = typeof(bool),
                Position = 3,
                HasDefaultValue = false,
                DefaultValue = default(bool)
            };
            
            parameters[4] = new()
            {
                Name = "roomTemplate",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.RoomTemplateGrid2D),
                Position = 4,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Grid2D.RoomTemplateGrid2D)
            };
            
            parameters[5] = new()
            {
                Name = "roomDescription",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D),
                Position = 5,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D)
            };
            
            parameters[6] = new()
            {
                Name = "transformation",
                ParameterType = typeof(global::Edgar.Geometry.TransformationGrid2D),
                Position = 6,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.TransformationGrid2D)
            };
            
            return parameters;
        }
    }
}
