// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LayoutContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.Geometry.RectangleGrid2D>? _RectangleGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.Geometry.RectangleGrid2D> RectangleGrid2D
        {
            get => _RectangleGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.Geometry.RectangleGrid2D>)Options.GetTypeInfo(typeof(global::Edgar.Geometry.RectangleGrid2D));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.Geometry.RectangleGrid2D> Create_RectangleGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.Geometry.RectangleGrid2D>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.Geometry.RectangleGrid2D> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.Geometry.RectangleGrid2D>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.Geometry.RectangleGrid2D((global::Edgar.Geometry.Vector2Int)args[0], (global::Edgar.Geometry.Vector2Int)args[1]),
                    PropertyMetadataInitializer = _ => RectangleGrid2DPropInit(options),
                    ConstructorParameterMetadataInitializer = RectangleGrid2DCtorParamInit,
                    SerializeHandler = RectangleGrid2DSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.Geometry.RectangleGrid2D>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] RectangleGrid2DPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[6];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).Center,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Center",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).Area,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Area",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).Width,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Width",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).Height,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Height",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info3);

            var info4 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = false,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).A,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "A",
                JsonPropertyName = null
            };
            
            properties[4] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info4);

            var info5 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = false,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.Geometry.RectangleGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.Geometry.RectangleGrid2D)obj).B,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "B",
                JsonPropertyName = null
            };
            
            properties[5] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info5);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void RectangleGrid2DSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.Geometry.RectangleGrid2D value)
        {
            writer.WriteStartObject();

            writer.WritePropertyName(PropName_Center);
            Vector2IntSerializeHandler(writer, ((global::Edgar.Geometry.RectangleGrid2D)value).Center);
            writer.WriteNumber(PropName_Area, ((global::Edgar.Geometry.RectangleGrid2D)value).Area);
            writer.WriteNumber(PropName_Width, ((global::Edgar.Geometry.RectangleGrid2D)value).Width);
            writer.WriteNumber(PropName_Height, ((global::Edgar.Geometry.RectangleGrid2D)value).Height);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] RectangleGrid2DCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[2];

            parameters[0] = new()
            {
                Name = "a",
                ParameterType = typeof(global::Edgar.Geometry.Vector2Int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.Vector2Int)
            };
            
            parameters[1] = new()
            {
                Name = "b",
                ParameterType = typeof(global::Edgar.Geometry.Vector2Int),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.Vector2Int)
            };
            
            return parameters;
        }
    }
}
