// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D>? _DoorGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D> DoorGrid2D
        {
            get => _DoorGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D> Create_DoorGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D((global::Edgar.Geometry.Vector2Int)args[0], (global::Edgar.Geometry.Vector2Int)args[1], (global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)args[2], (global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)args[3]),
                    PropertyMetadataInitializer = _ => DoorGrid2DPropInit(options),
                    ConstructorParameterMetadataInitializer = DoorGrid2DCtorParamInit,
                    SerializeHandler = DoorGrid2DSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] DoorGrid2DPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)obj).From,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "From",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.Vector2Int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)obj).To,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "To",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.Vector2Int>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)obj).Socket,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Socket",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)obj).Type,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Type",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void DoorGrid2DSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WritePropertyName(PropName_From);
            Vector2IntSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)value).From);
            writer.WritePropertyName(PropName_To);
            Vector2IntSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)value).To);
            writer.WritePropertyName(PropName_Socket);
            IDoorSocketSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)value).Socket);
            writer.WritePropertyName(PropName_Type);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorGrid2D)value).Type, DoorType);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] DoorGrid2DCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[4];

            parameters[0] = new()
            {
                Name = "from",
                ParameterType = typeof(global::Edgar.Geometry.Vector2Int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.Vector2Int)
            };
            
            parameters[1] = new()
            {
                Name = "to",
                ParameterType = typeof(global::Edgar.Geometry.Vector2Int),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.Vector2Int)
            };
            
            parameters[2] = new()
            {
                Name = "socket",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket),
                Position = 2,
                HasDefaultValue = true,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)
            };
            
            parameters[3] = new()
            {
                Name = "type",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.DoorType),
                Position = 3,
                HasDefaultValue = true,
                DefaultValue = (global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)(0)
            };
            
            return parameters;
        }
    }
}
