// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D>? _DoorLineGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D> DoorLineGrid2D
        {
            get => _DoorLineGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D> Create_DoorLineGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D((global::Edgar.Geometry.OrthogonalLineGrid2D)args[0], (int)args[1], (global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)args[2], (global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)args[3]),
                    PropertyMetadataInitializer = _ => DoorLineGrid2DPropInit(options),
                    ConstructorParameterMetadataInitializer = DoorLineGrid2DCtorParamInit,
                    SerializeHandler = DoorLineGrid2DSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] DoorLineGrid2DPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.Geometry.OrthogonalLineGrid2D>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)obj).Line,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Line",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.Geometry.OrthogonalLineGrid2D>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)obj).Length,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Length",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)obj).DoorSocket,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "DoorSocket",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)obj).Type,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Type",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.Doors.DoorType>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void DoorLineGrid2DSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D value)
        {
            writer.WriteStartObject();

            writer.WritePropertyName(PropName_Line);
            OrthogonalLineGrid2DSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)value).Line);
            writer.WriteNumber(PropName_Length, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)value).Length);
            writer.WritePropertyName(PropName_DoorSocket);
            IDoorSocketSerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)value).DoorSocket);
            writer.WritePropertyName(PropName_Type);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.DoorLineGrid2D)value).Type, DoorType);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] DoorLineGrid2DCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[4];

            parameters[0] = new()
            {
                Name = "line",
                ParameterType = typeof(global::Edgar.Geometry.OrthogonalLineGrid2D),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.Geometry.OrthogonalLineGrid2D)
            };
            
            parameters[1] = new()
            {
                Name = "length",
                ParameterType = typeof(int),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            parameters[2] = new()
            {
                Name = "doorSocket",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket),
                Position = 2,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Common.Doors.IDoorSocket)
            };
            
            parameters[3] = new()
            {
                Name = "type",
                ParameterType = typeof(global::Edgar.GraphBasedGenerator.Common.Doors.DoorType),
                Position = 3,
                HasDefaultValue = false,
                DefaultValue = default(global::Edgar.GraphBasedGenerator.Common.Doors.DoorType)
            };
            
            return parameters;
        }
    }
}
