// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>? _DictionaryInt32RoomDescriptionGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>> DictionaryInt32RoomDescriptionGrid2D
        {
            get => _DictionaryInt32RoomDescriptionGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>> Create_DictionaryInt32RoomDescriptionGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>> jsonTypeInfo))
            {
                var info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>(),
                    SerializeHandler = null
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateDictionaryInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>, int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
