// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>>? _LevelDescriptionGrid2DInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>> LevelDescriptionGrid2DInt32
        {
            get => _LevelDescriptionGrid2DInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>> Create_LevelDescriptionGrid2DInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>>
                {
                    ObjectCreator = () => new global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>(),
                    ObjectWithParameterizedConstructorCreator = null,
                    PropertyMetadataInitializer = _ => LevelDescriptionGrid2DInt32PropInit(options),
                    ConstructorParameterMetadataInitializer = null,
                    SerializeHandler = LevelDescriptionGrid2DInt32SerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] LevelDescriptionGrid2DInt32PropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[8];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).MinimumRoomDistance,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).MinimumRoomDistance = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "MinimumRoomDistance",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.List<global::System.Collections.Generic.List<int>>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).Clusters,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).Clusters = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Clusters",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::System.Collections.Generic.List<int>>>(options, info1);

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).Constraints,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).Constraints = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Constraints",
                JsonPropertyName = null
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>(options, info2);

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode?>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).RoomTemplateRepeatModeDefault,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).RoomTemplateRepeatModeDefault = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "RoomTemplateRepeatModeDefault",
                JsonPropertyName = null
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode?>(options, info3);

            var info4 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode?>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).RoomTemplateRepeatModeOverride,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)obj).RoomTemplateRepeatModeOverride = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "RoomTemplateRepeatModeOverride",
                JsonPropertyName = null
            };
            
            properties[4] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::Edgar.GraphBasedGenerator.Common.RoomTemplateRepeatMode?>(options, info4);

            var info5 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).Name,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).Name = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Name",
                JsonPropertyName = null
            };
            
            properties[5] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info5);

            var info6 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>
            {
                IsProperty = false,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).roomDescriptions,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).roomDescriptions = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "roomDescriptions",
                JsonPropertyName = null
            };
            
            properties[6] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.Dictionary<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>>(options, info6);

            var info7 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>
            {
                IsProperty = false,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).passages,
                Setter = static (obj, value) => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)obj).passages = value!,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "passages",
                JsonPropertyName = null
            };
            
            properties[7] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>(options, info7);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void LevelDescriptionGrid2DInt32SerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_MinimumRoomDistance, ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)value).MinimumRoomDistance);
            writer.WritePropertyName(PropName_Clusters);
            ListListInt32SerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)value).Clusters);
            writer.WritePropertyName(PropName_Constraints);
            ListIGeneratorConstraintGrid2DInt32SerializeHandler(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)value).Constraints);
            writer.WritePropertyName(PropName_RoomTemplateRepeatModeDefault);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)value).RoomTemplateRepeatModeDefault, NullableRoomTemplateRepeatMode);
            writer.WritePropertyName(PropName_RoomTemplateRepeatModeOverride);
            global::System.Text.Json.JsonSerializer.Serialize(writer, ((global::Edgar.GraphBasedGenerator.Grid2D.LevelDescriptionGrid2D<int>)value).RoomTemplateRepeatModeOverride, NullableRoomTemplateRepeatMode);
            writer.WriteString(PropName_Name, ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>)value).Name);

            writer.WriteEndObject();
        }
    }
}
