// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>? _PassageInt32RoomDescriptionGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage> PassageInt32RoomDescriptionGrid2D
        {
            get => _PassageInt32RoomDescriptionGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>)Options.GetTypeInfo(typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage> Create_PassageInt32RoomDescriptionGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage((int)args[0], (int)args[1]),
                    PropertyMetadataInitializer = _ => PassageInt32RoomDescriptionGrid2DPropInit(options),
                    ConstructorParameterMetadataInitializer = PassageInt32RoomDescriptionGrid2DCtorParamInit,
                    SerializeHandler = PassageInt32RoomDescriptionGrid2DSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] PassageInt32RoomDescriptionGrid2DPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[2];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage)obj).Room1,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Room1",
                JsonPropertyName = null
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info0);

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<int>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage),
                Converter = null,
                Getter = static obj => ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage)obj).Room2,
                Setter = null,
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Room2",
                JsonPropertyName = null
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<int>(options, info1);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void PassageInt32RoomDescriptionGrid2DSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteNumber(PropName_Room1, ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage)value).Room1);
            writer.WriteNumber(PropName_Room2, ((global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage)value).Room2);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] PassageInt32RoomDescriptionGrid2DCtorParamInit()
        {
            var parameters = new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[2];

            parameters[0] = new()
            {
                Name = "room1",
                ParameterType = typeof(int),
                Position = 0,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            parameters[1] = new()
            {
                Name = "room2",
                ParameterType = typeof(int),
                Position = 1,
                HasDefaultValue = false,
                DefaultValue = default(int)
            };
            
            return parameters;
        }
    }
}
