// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>? _ListIGeneratorConstraintGrid2DInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>> ListIGeneratorConstraintGrid2DInt32
        {
            get => _ListIGeneratorConstraintGrid2DInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>> Create_ListIGeneratorConstraintGrid2DInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>> jsonTypeInfo))
            {
                var info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>(),
                    SerializeHandler = ListIGeneratorConstraintGrid2DInt32SerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>, global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void ListIGeneratorConstraintGrid2DInt32SerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Grid2D.IGeneratorConstraintGrid2D<int>>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();

            for (int i = 0; i < value.Count; i++)
            {
                IGeneratorConstraintGrid2DInt32SerializeHandler(writer, value[i]);
            }

            writer.WriteEndArray();
        }
    }
}
