// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>? _ListPassageInt32RoomDescriptionGrid2D;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>> ListPassageInt32RoomDescriptionGrid2D
        {
            get => _ListPassageInt32RoomDescriptionGrid2D ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>)Options.GetTypeInfo(typeof(global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>> Create_ListPassageInt32RoomDescriptionGrid2D(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>> jsonTypeInfo))
            {
                var info = new global::System.Text.Json.Serialization.Metadata.JsonCollectionInfoValues<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>>
                {
                    ObjectCreator = () => new global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>(),
                    SerializeHandler = ListPassageInt32RoomDescriptionGrid2DSerializeHandler
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateListInfo<global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>, global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>(options, info);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void ListPassageInt32RoomDescriptionGrid2DSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::System.Collections.Generic.List<global::Edgar.GraphBasedGenerator.Common.LevelDescriptionBase<int, global::Edgar.GraphBasedGenerator.Grid2D.RoomDescriptionGrid2D>.Passage>? value)
        {
            if (value == null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartArray();

            for (int i = 0; i < value.Count; i++)
            {
                PassageInt32RoomDescriptionGrid2DSerializeHandler(writer, value[i]);
            }

            writer.WriteEndArray();
        }
    }
}
