// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace Edgar.NativeAotLib
{
    public partial class LevelDescriptionContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Length = global::System.Text.Json.JsonEncodedText.Encode("Length");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Room1 = global::System.Text.Json.JsonEncodedText.Encode("Room1");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Room2 = global::System.Text.Json.JsonEncodedText.Encode("Room2");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_From = global::System.Text.Json.JsonEncodedText.Encode("From");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_To = global::System.Text.Json.JsonEncodedText.Encode("To");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Socket = global::System.Text.Json.JsonEncodedText.Encode("Socket");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Type = global::System.Text.Json.JsonEncodedText.Encode("Type");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Line = global::System.Text.Json.JsonEncodedText.Encode("Line");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_DoorSocket = global::System.Text.Json.JsonEncodedText.Encode("DoorSocket");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_MinimumRoomDistance = global::System.Text.Json.JsonEncodedText.Encode("MinimumRoomDistance");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Clusters = global::System.Text.Json.JsonEncodedText.Encode("Clusters");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Constraints = global::System.Text.Json.JsonEncodedText.Encode("Constraints");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_RoomTemplateRepeatModeDefault = global::System.Text.Json.JsonEncodedText.Encode("RoomTemplateRepeatModeDefault");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_RoomTemplateRepeatModeOverride = global::System.Text.Json.JsonEncodedText.Encode("RoomTemplateRepeatModeOverride");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Name = global::System.Text.Json.JsonEncodedText.Encode("Name");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Doors = global::System.Text.Json.JsonEncodedText.Encode("Doors");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_DoorLines = global::System.Text.Json.JsonEncodedText.Encode("DoorLines");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_IsCorridor = global::System.Text.Json.JsonEncodedText.Encode("IsCorridor");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_RoomTemplates = global::System.Text.Json.JsonEncodedText.Encode("RoomTemplates");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_Outline = global::System.Text.Json.JsonEncodedText.Encode("Outline");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_RepeatMode = global::System.Text.Json.JsonEncodedText.Encode("RepeatMode");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_AllowedTransformations = global::System.Text.Json.JsonEncodedText.Encode("AllowedTransformations");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_DoorLength = global::System.Text.Json.JsonEncodedText.Encode("DoorLength");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_CornerDistance = global::System.Text.Json.JsonEncodedText.Encode("CornerDistance");
    }
}
